stages:
  - build
  - test
  - deploy_staging
  - test_staging
  - deploy_production
  
image_build:
  stage: build
  script:
    - echo "Building Docker image for Canario-Shop"
    - docker build -t canario-shop:$CI_PIPELINE_ID .

code_test:
  stage: test
  script:
    - cd app
    - cat main.py

deploy_staging:
  stage: deploy_staging
  script:
    - docker run -d -p 8000:80 --name canario-shop-staging-$CI_PIPELINE_ID canario-shop:$CI_PIPELINE_ID

test_staging:
  stage: test_staging
  script:
    - sleep 10 
    - curl http://10.196.38.192:8000  

deploy_production:
  stage: deploy_production
  script:
    - docker stop canario-shop-staging-$CI_PIPELINE_ID
    - docker rm canario-shop-staging-$CI_PIPELINE_ID
    - docker run -d -p 80 --name canario-shop-production-$CI_PIPELINE_ID canario-shop:$CI_PIPELINE_ID