stages:
  - build
  - test
  - deploy_staging
  - test_staging
  - deploy_production
  #- clean-production # I dont want to keep deployment now
  
image_build:
  stage: build
  script:
    - echo "Building Docker image for Canario-Shop"
    - docker build -t canario-shop:$CI_PIPELINE_ID .

code_test:
  stage: test
  script:
    - cd app
    - cat main.py

deploy_staging:
  stage: deploy_staging
  script:
    - docker run -d -p 8000:80 --name canario-shop-staging-$CI_PIPELINE_ID canario-shop:$CI_PIPELINE_ID 
    - docker logs canario-shop-staging-$CI_PIPELINE_ID


test_staging:
  stage: test_staging
  script:
    - sleep 10 
    - curl http://10.196.38.192:8000  

deploy_production:
  stage: deploy_production
  script:
    - docker stop canario-shop-staging-$CI_PIPELINE_ID
    - docker rm canario-shop-staging-$CI_PIPELINE_ID
    #- docker run -d -p 80 --name canario-shop-production-$CI_PIPELINE_ID canario-shop:$CI_PIPELINE_ID 
    # this can be deplo shop1, can add deploy shop2 with different port.. representing webservers.. down use flags and server them differently
    #- docker run --name canario-shop-production1-$CI_PIPELINE_ID -p 8003:80 -e SHOW_FLASHSALE=1 -e SHOW_PREMIUM=0 -e   USE_MEMCACHE=Y -e MEMCACHE_SERVER=10.196.38.192 -e INFO_PORT=8003 -d canario-shop:$CI_PIPELINE_ID
    #- docker run --name canario-shop-production2-$CI_PIPELINE_ID -p 8004:80 -e SHOW_FLASHSALE=0 -e SHOW_PREMIUM=1 -e   USE_MEMCACHE=Y -e MEMCACHE_SERVER=10.196.38.192 -e INFO_PORT=8004 -d canario-shop:$CI_PIPELINE_ID
    # - docker  service create --replicas=2 --name canario-shop-production1-$CI_PIPELINE_ID -p 8003:80 -e SHOW_FLASHSALE=0 -e SHOW_PREMIUM=1 -e   USE_MEMCACHE=Y -e MEMCACHE_SERVER=10.196.38.192 -e INFO_PORT=8003 -d canario-shop:$CI_PIPELINE_ID
    # - docker service create --replicas=2 --name canario-shop-production2-$CI_PIPELINE_ID -p 8004:80 -e SHOW_FLASHSALE=0 -e SHOW_PREMIUM=1 -e   USE_MEMCACHE=Y -e MEMCACHE_SERVER=10.196.38.192 -e INFO_PORT=8004 -d canario-shop:$CI_PIPELINE_ID
    - docker service create --replicas=2 --name canario-shop-production1-$CI_PIPELINE_ID -p 8003:80 -e SHOW_FLASHSALE=$SHOW_FLASHSALE -e SHOW_PREMIUM=$SHOW_PREMIUM -e USE_MEMCACHE=$USE_MEMCACHE -e MEMCACHE_SERVER=10.196.38.192 -e INFO_PORT=8003 -d canario-shop:$CI_PIPELINE_ID
    - docker service create --replicas=2 --name canario-shop-production2-$CI_PIPELINE_ID -p 8004:80 -e SHOW_FLASHSALE=$SHOW_FLASHSALE -e SHOW_PREMIUM=$SHOW_PREMIUM -e USE_MEMCACHE=$USE_MEMCACHE -e MEMCACHE_SERVER=10.196.38.192 -e INFO_PORT=8004 -d canario-shop:$CI_PIPELINE_ID






#deploy_productionFF:
  #stage: deploy_production
  #script:
    #- docker run --name canario-shop-productionFF-$CI_PIPELINE_ID -p 8001:80 -e SHOW_FLASHSALE=1 -e SHOW_PREMIUM=1 -e   USE_MEMCACHE=Y -e MEMCACHE_SERVER=10.196.38.192 -d canario-shop:$CI_PIPELINE_ID

run-caddy:
  stage: deploy_production
  script:
    - echo "http://:80 {" > Caddyfile
    - echo "  reverse_proxy 10.196.38.192:8003 10.196.38.192:8004" >> Caddyfile
    - echo "}" >> Caddyfile
    - docker pull caddy/caddy:latest
    - docker run -d -p 80:80 --name caddy-$CI_PIPELINE_ID -v $(pwd)/Caddyfile:/etc/caddy/Caddyfile caddy/caddy:latest



# clean_containers
#     stage: clean-production
#     script:
#       - docker stop canario-shop-production-$CI_PIPELINE_ID
#       - docker rm canario-shop-production-$CI_PIPELINE_ID


